name: Hugo on GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

# Set the needed permissions
permissions:
  contents: read
  pages: write
  id-token: write

# Cancel running deployments if a new one is issued.
concurrency:
  group: pages
  cancel-in-progress: true

env:
  targetURL: "https://oeysan.github.io/c2z4inn/"
  
jobs:
  build:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install renv
        uses: r-lib/actions/setup-renv@v2

      - name: Get Hugo version
        id: hugo_version
        run: |
          version=$(cat .Rprofile | grep hugo.version | cut -d'"' -f2 )
          echo "Hugo version in .Rprofile is $version"
          echo "value=${version}" >>$GITHUB_OUTPUT

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ steps.hugo_version.outputs.value }}
          extended: true
          
      - name: Install Dart Sass
        run: sudo snap install dart-sass
          
      - name: Build site
        run: |
          sed -i "s|baseURL: \"/\"|baseURL: \"${{ env.targetURL }}\"|" config.yaml
          sed -i "s|subfolder: \"/|subfolder: \"/$(basename ${{ env.targetURL }})/|" config.yaml
          hugo -b ${{ env.targetURL }}
          touch public/.nojekyll
        shell: bash
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
